### ISSUE TITLE
An argument in mldr_evaluate to specify if the predictions given as input are bipartitions or rankings

### ISSUE THREAD

**Issue by alessanderbotti** [fcharte/mldr#25]
An execution of the mldr_evaluate function calculates two kinds of metrics (the bipartition based and ranking based evaluation metrics), but (if I understood well) the predictions given as input are bipartitions or rankings, but not both. Would it make sense to have an argument at mldr_evaluate in which one specifies if the output of the classifier is a bipartition or a ranking, in order to avoid calculating and showing unnecessary metrics?

Alternatively, I think it would be easier to read the output of mldr_evaluate if the bipartition based and ranking based evaluation metrics were grouped under two sublists (e.g., "bipartition metrics" and "ranking metrics").

Sorry if this is nonsense, and thanks for mldr!

**Comment by fdavidcl** [comment]
Hi, sorry for the late answer.

We've discussed the possibility of classifying those evaluation metrics, but are reluctant to introduce any changes that would break backwards-compatibility. Also, it could be desirable to have other classifications as well (e.g. as sample-based vs. label-based), so it's hard to suit everybody's needs here.

About the possibility of a parameter to prevent calculating certain measures, we believe it would be of little use since different sets of metrics could be desired depending on the experimentation performed. It might be a better idea to expose each individual function calculating each measure so that users can choose, but we'd still have to discuss this.

Sorry that we couldn't bring these ideas to mldr, I hope it's not much of a problem for you. Thanks for suggesting them anyway!

**Comment by alessanderbotti** [comment]
No problem at all, you are doing a great work on mldr!
I am new to data classification, and a bit unused to wait for long computations to finish. So, this suggestion was an attempt to speed up my tests. However, I understand that the calculations of these evaluation metrics may not have such a bad time complexity after all. Thanks for considering the suggestion!
