### ISSUE TITLE
Question about implementation of Measures

### ISSUE THREAD

**Issue by QuayAu** [fcharte/mldr#28]
Hi!
I have a few questions/remarks about the implementation of the example based measures _Accuracy_, _Precision_ and _Recall_. 
- I am wondering why the numerators in your implementation are different.
- Could you explain the denominator of your implementation of _Accuracy_? Why is it the sum of predicted positives and predicted negatives? Shouldn't the code for  _Accuracy_ be something like:

```
mldr_Accuracy <- function(counters) {
  mean((counters$TruePositives) / (counters$PredictedPositives + counters$RealPositives - counters$TruePositives))
}
```

I added your source code and a screenshot of your vignette of the three measures below:

![measures](https://cloud.githubusercontent.com/assets/15329438/12942695/42fc681e-cfdd-11e5-8212-9277a41b3d01.png)

```
# Calculate example based accuracy
mldr_Accuracy <- function(counters) {
  mean((counters$TruePositives + counters$TrueNegatives) / (counters$PredictedPositives + counters$PredictedNegatives))
}

# Calculate example based precision
mldr_Precision <- function(counters) {
  mean(counters$TruePositives / counters$PredictedPositives, na.rm = TRUE)
}

# Calculate example based recall
mldr_Recall <- function(counters) {
  mean(counters$TruePositives / counters$RealPositives, na.rm  = TRUE)
}
```

**Comment by fdavidcl** [comment]
Indeed there seems to be something weird about that implementation. I'm looking into this, in case I missed something. Thank you very much for letting us know.

**Comment by rivolli** [comment]
Other measure that I suggest review is FMeasure, because the mean function is used with the parameters na.rm = TRUE  

With this, when the precision and recall are 0 the element is ignored. Suppose I have 10 examples and in 3 the precision and recall values are 0, then the mean will be calculated with 7 examples but the total of examples were 10.

[]'s

**Comment by fdavidcl** [comment]
I'm picking up this issue again (sorry for the delay). So just to give some updates:

- our current implementation of Accuracy does not follow the definition and is being reworked,
- our current implementation of FMeasure does not follow the definition either, it's being reworked,
- Precision and Recall were correctly implemented as defined in many other papers on the field, the paper in the opening post actually has a typo 😖 ,
- the use of `na.rm` in order to ignore undefined values is probably going to be left as a user parameter; for the record, MULAN makes a different decision when denominators are 0 according to whether the prediction was accurate. I'll try to provide this option as well.
