### ISSUE TITLE
circular plot in mldr

### ISSUE THREAD

**Issue by omsaif2009** [fcharte/mldr#29]
Hi,
I am trying to use the package. I did understand the LB histogram, for example. Numbers show the label frequencies. However, I don't understand numbers shown in each arc of the circular plot. They don't represent label frequencies and don't sum to the total number of instances in the dataset. Additionally, some labels don't appear in this plot. For example, I tried to plot the scene dataset and only 5 labels out of 6 were shown in the LC plot. Could you please elaborate?
Reem

**Comment by fdavidcl** [comment]
Hello,

Thanks for your question. The circular plot generated by *mldr* is a "Label Concurrence" (or label interaction) plot, which means it's expected to represent not labels as such but their interactions with one another. Consider the following plot (from the emotions dataset):

![emotions LC plot](https://cloud.githubusercontent.com/assets/909629/14790949/f48b6802-0b13-11e6-81f9-f43bf33a7378.png)

Let's focus on the *sad-lonely* label, for example. The number shown should count the number of interactions with the rest of labels, so if we select all instances in which the *sad-lonely* label is active, and then sum all label columns except *sad-lonely*, we will get to the same amount:

~~~r
> sum(emotions$dataset[emotions$dataset$"sad-lonely" == 1, emotions$labels$index]) - sum(emotions$dataset$"sad-lonely")
[1] 231
~~~
which is what we expected.

As for labels not showing up in the plot, since most datasets have numerous labels, the *plot* function defaults to the labels with most interactions according to the *SCUMBLE* measure. You can select a different set of labels via the *labelIndices* parameter, as shown here:

~~~r
> plot(emotions) # Plots only labels with high SCUMBLE
> plot(scene, labelIndices = scene$labels$index) # Plots all labels
> plot(genbase, labelIndices = genbase$labels$index[1:10]) # Plots info of first 10 labels
~~~

I hope this clears up the confusion. We may modify the documentation to improve information on this topic.

Best,
David

**Comment by omsaif2009** [comment]
Fantastic!! That's clear now. 
Just to clarify something, still I couldn't plot all labels in scene dataset when I chose LC plot. As this label doesn't have any interaction with other labels.
Thanks

**Comment by fdavidcl** [comment]
Exactly, if the count of interactions of a label is 0, it won't be displayed in the plot.
