### ISSUE TITLE
categorical attribute

### ISSUE THREAD

**Issue by rivolli** [fcharte/mldr#31]
Hello

I'm in trouble regarding the use of categorical attributes in mldr datasets.
The mldr function ignore the levels containing in the arff file.

For example, I get the flags.arrf and remove almost all instances (I left just 10)
When I read the dataset using mldr, if I get a categorical attribute like "language" is not possible know about the possible values.

For example: 

> test <- mldr("flags-test")
> test$dataset[,"language"]
> [1] "6"  "7"  "2"  "8"  "10" "1"  "10" "6"  "10" "1"

But I expected something like this:

> test$dataset[,"language"]
> [1] 6  7  2  8  10 1  10 6  10 1 
> Levels: 1 10 2 3 4 5 6 7 8 9

**Comment by fdavidcl** [comment]
Hi,

6c5160c and e4ce52a seem a reasonable fix. When this gets merged into the package, you will need to use the `stringsAsFactors = T` option in order to get the behavior you described:

~~~R
test <- mldr("flags-test", stringsAsFactors = T)
str(fl$dataset$language)
 Factor w/ 10 levels "1","10","2","3",..: 2 7 9 1 7 2 1 1 3 3 ...
~~~

Thanks for the suggestion!
