### ISSUE TITLE
Did the meaning of recall change?

### ISSUE THREAD

**Issue by AlexEngelhardt** [fcharte/mldr#45]
Hi there,

I am having some trouble understanding the new implementation of the `recall()` function (I'm really bad with functionals).

In particular, the following sample data of true and predicted labels gives a different recall in the old vs. new implementation:

```r
multi.y <-
structure(c(TRUE, FALSE, FALSE, TRUE, TRUE, TRUE, FALSE, TRUE
), .Dim = c(4L, 2L), .Dimnames = list(c("1", "2", "3", "4"), 
    c("tar1.multilabel", "tar2.multilabel")))

multi.p <-
structure(c(TRUE, FALSE, FALSE, FALSE, FALSE, TRUE, FALSE, TRUE
), .Dim = c(4L, 2L), .Dimnames = list(c("1", "2", "3", "4"), 
    c("tar1.multilabel", "tar2.multilabel")))

### old mldr

counters = data.frame(
  RealPositives = rowSums(multi.y),
  RealNegatives = rowSums(!multi.y),
  PredictedPositives = rowSums(multi.p),
  PredictedNegatives = rowSums(!multi.p),
  TruePositives = rowSums(multi.y & multi.p),
  TrueNegatives = rowSums(!multi.y & !multi.p))

# Calculate example based recall
mldr_Recall <- function(counters) {
  mean(counters$TruePositives / counters$RealPositives, na.rm  = TRUE)
}

mldr_Recall(counters)  # 0.66667

### new mldr

mldr::recall(multi.y, multi.p)  # 0.75
```

The `mlr` package uses mldr for a few tests [here](https://github.com/mlr-org/mlr/blob/master/tests/testthat/test_base_measures.R#L734), and the updates caused a few of its tests to fail. 

Could you explain what happened there? I couldn't figure it out myself, unfortunately.

Thanks in advance!

**Comment by AlexEngelhardt** [comment]
I just found out that this line does what I want:

```r
mldr::recall(multi.y, multi.p, undefined_value = "ignore")  # 0.66667
```

Could you just confirm that adding this argument is equivalent to the default behavior of the old `mldr_Recall()` function?

**Comment by fdavidcl** [comment]
Hi!

The meaning of recall hasn't changed, but we've adjusted the way it deals with cases where denominators are 0 (these are edge cases but may slightly vary results in real experimentations). The old behavior can be retrieved, as you just discovered, by using the parameter `undefined_value = "ignore"`:

~~~r
> mldr::recall(multi.y, multi.p, undefined_value = "ignore")  # 0.75
[1] 0.6666667
Warning message:
In mldr::recall(multi.y, multi.p, undefined_value = "ignore") :
  Undefined values will be ignored, mean will be computed with the rest.
~~~

The current default behavior is to more fairly "diagnose" these cases, and assign a 1 value to cases where the classifier correctly outputs no labels, and 0 otherwise. Since this is the behavior of the widely used implementation in MULAN, we decided it should be the default so as to ease fair comparisons for classifiers among R and Java.

**Comment by AlexEngelhardt** [comment]
Thanks a lot! This helps, and I (think I) fixed the respective test.

There's another one with our F1-measure comparing to your `fmeasure`, which I haven't been able to fix so far. The `mlr` implementation works with the absolute counts in the truth and response labels, and I can't bridge the gap to how to duplicate this computation with your code. 

This is what `mlr` does as of now:

```r
measureMultiLabelF1 = function(truth, response) {
  numerator = 2 * rowSums(truth & response)
  denominator = rowSums(truth + response)
  mean(ifelse(denominator == 0, 1, numerator / denominator))
}

truth <- matrix(c(T, F, F, T, T, T, F, T), ncol=2)
response <- matrix(c(T, F, F, F, F, T, F, T), ncol=2)

measureMultiLabelF1(truth, response)  # 0.833333
```

I twisted a few parameters in `mldr` but couldn't reproduce that number. Do you have a hint on how I can reproduce it?

**Comment by fdavidcl** [comment]
First of all, thanks for taking the time to look into this, and sorry we broke those tests.

I've tried a few things and I think both implementations are following correct definitions of F1-score [[source](https://en.wikipedia.org/wiki/F1_score#Formulation)]. However, the definitions are not strictly equivalent. The problem lies again in the undefined cases. Since we are using the *(2 Prec Rec)/(Prec + Rec)* definition, our implementation deals with more intermediate undefined cases: those for *Prec* and *Rec*, i.e. when *TP + FN = 0* or *TP + FP = 0*. Meanwhile, the `mlr` version is undefined only if *TP + FP + FN = 0*. This means that, under certain conditions, **there is no way for both implementations to obtain the same results** 😕 

I've put together a slightly more complex example of this, including an implementation of the alternative definition of F1-score in `mldr` style:
~~~r
# Get the true labels in emotions
truth <- as.matrix(emotions$dataset[, emotions$labels$index])
response <- truth
# introduce some noise
seed(1)
noised_labels <- cbind(sample(1:593, 200, replace = TRUE), sample(1:6, 200, replace = TRUE))
response[noised_labels] <- sample(0:1, 200, replace = TRUE)

mlrAltF1 <- function(truth, response) {
  prec <- mlr::measureMultilabelPPV(truth, response)
  rec <- mlr::measureMultilabelTPR(truth, response)
  2 * prec * rec / (prec + rec)
}

base_fmeasure = function(tp, fp, tn, fn, ...) {
  if (tp + fp + fn == 0)
    1
  else
    2 * tp / (2 * tp + fn + fp)
}

instance_fmeasure = mldr:::instance_avg(base_fmeasure)

mldr::fmeasure(truth, response, undefined_value = "ignore") # 0.9312711
mlrAltF1(truth, response) # 0.9312711
mlr::measureMultiLabelF1(truth, response) # 0.9105396
instance_fmeasure(truth, response) # 0.9105396
~~~

When using the *Prec/Rec* definition we obtain the same results than `mldr`, but if we define F1-score in terms of type I and type II errors, we obtain the results from `mlr`. This means that there are rows which do not imply a valid Precision or Recall value but do have a valid F1-score. This would imply that the second definition actually covers more examples than the *Prec/Rec* one.

By the way, that definition of `instance_measure` would be an option if you need another implementation to compare against.

Hope this helps clear the problem a bit. I still would like both packages to show the same results, so we'll have to consider modifying our current `fmeasure`.

**Comment by AlexEngelhardt** [comment]
Thanks a lot! That clears it up for me.

I asked [over at mlr](https://github.com/mlr-org/mlr/pull/2161#issuecomment-364728054) whether the mlr implementation might be changed. Your `mlrAltF1` looks good to me, but I don't have the bird's eye view to make the decision whether or not to change the mlr version.

**Comment by fdavidcl** [comment]
Ok, great! I would be more inclined to change our implementation, still, since it would seem to be less prone to edge cases. The decision in `mlr` of course is up to their maintainers.
