### ISSUE TITLE
v0.4.1 breaks mlr test

### ISSUE THREAD

**Issue by pat-s** [fcharte/mldr#47]
Hi, 

just wanted to let you know that the recent update broke one of our tests:

https://github.com/mlr-org/mlr/issues/2524

Haven't yet taken a closer look if the problem is on our side or yours. Could you reply briefly which side should take action? :)
Thanks.

**Comment by fdavidcl** [comment]
Hi, thanks for the heads-up.

In this version we adjusted `mldr::accuracy` to match the behavior from MULAN and the definition in [this paper](https://sci2s.ugr.es/sites/default/files/ficherosPublicaciones/1790_2015-Neuro-Charte-MultiLabel_Imbalanced.pdf). The broken test seems to be comparing `Accuracy` to `1 - HammingLoss`, which apparently is only equal in the binary case (according to [this discussion](https://stats.stackexchange.com/a/341059), but I'd have to check the formula to be sure). 

mlr currently doesn't have a test comparing `mldr::accuracy` to `measureMultilabelACC` (https://github.com/cran/mlr/blob/41b860fe59a995f35bdb14af73956b6b2b55001a/tests/testthat/test_base_measures.R#L711), but it could be added since they should be the same now. If this test passes, I think there shouldn't be a need for the broken one.

**Comment by pat-s** [comment]
Thanks for the quick response. I'll take a closer look in the next days!

**Comment by pat-s** [comment]
Comparing `mldr::accurary` to `measureMultilabelACC` fails: https://travis-ci.org/mlr-org/mlr/jobs/485008680

I am not into multilabel measures. Do you know if the problem is on our side here?

**Comment by fdavidcl** [comment]
The problem was on our side in this case, I've amended it and submitted the fixed version to CRAN, which should be up in a few hours. This new version should mimic the behavior of both mlr and MULAN implementations (I've checked the broken test and it is fixed as well). Sorry about all the trouble.

**Comment by pat-s** [comment]
The update seems to have solved the initial issue so that no further action is required now. Thanks!
